### ISSUE TITLE
Server boots player off when right clicking anywhere while in render radius of portal [1.16.4]

### ISSUE THREAD

**Issue by Jarfeh** [TheEpicBlock/immersive-cursedness#10]
~~When attempting to place anything with the portal in the player's view, the player will be booted before the block is place.~~
This error pops up
![image](https://user-images.githubusercontent.com/58902941/102157177-de5fb300-3e33-11eb-8e36-af39704a826e.png)

Edit: So it appears right clicking anywhere near a portal, regardless if it's in view will cause the kick

**Comment by TheEpicBlock** [comment]
A patch for this was released on the [modrinth](https://modrinth.com/mod/lyiXgXNm/versions) page. It seems like I forgot to add it to gh, sorry for that, I'll add it once I have the time.

**Comment by Jarfeh** [comment]
Thanks
