### ISSUE TITLE
Compatibility issues with WorldEdit (Fabric)

### ISSUE THREAD

**Issue by xieve** [TheEpicBlock/immersive-cursedness#11]
Used mods: Fabric API, WorldEdit-Fabric, Immersive Cursedness

Running on openjdk-jre8-headless

[latest.log](https://github.com/TheEpicBlock/immersive-cursedness/files/5719350/latest.log)

Edit 2: Turns out copying from tmux is harder than I thought…

[tmux.log](https://github.com/TheEpicBlock/immersive-cursedness/files/5719366/tmux.log)

**Comment by TheEpicBlock** [comment]
I believe this is a mixin issue. It should be easily circumventable though

**Comment by TheEpicBlock** [comment]
Finally fixed with 1.3.1 :)
