### ISSUE TITLE
Lingering rendering bug

### ISSUE THREAD

**Issue by griffin4cats** [TheEpicBlock/immersive-cursedness#12]
After using this mod on the server and playing around with it a bit, one time when I went through the portal, the game stopped rendering any blocks. Relogging didn't fix it. The only way to force the server to render anything is to place a block or interact, and even then, that only shows the subchunk that I was interacting with (unless it's on a chunk or subchunk border). But strangely enough, particle effects from blocks around me kept rendering.

Even after I took the mod off of the server, this persisted. I had to restart my client in order to fix it!
Running lithium and phosphor on the server side, along with some minor ones.

I also have a suggestion: Instead of making this *server-side*, can you make a *client-side* version? One that saves chunks and remembers where the portals are linked, and renders it client-side, rather than the server having to send over the blocks on the other side, and not being able to send very much?

**Comment by TheEpicBlock** [comment]
I doubt the rendering issue is something I can change. This clearly originates on the client and I shouldn't be sending anything weird enough to trigger it :P
Making this client-side would be a completely different mod, and unfortunately I don't have any expertise in rendering, so it's unlikely that I'll create such a mod.
