### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ayzick** [TheEpicBlock/immersive-cursedness#13]
The mod crashes when i launch the game

**Comment by TheEpicBlock** [comment]
Could you please provide a crashlog?

**Comment by ayzick** [comment]
It just says
An unexpcted error has occured
Exit Code 0

**Comment by TheEpicBlock** [comment]
[Windows/Linux](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows)
[MacOs](https://fabricmc.net/wiki/player:tutorials:logs_ml:mac)
To upload the log, you can simply drag it into Github. Please make sure that the last time you launched the game resulted in a crash.

**Comment by ayzick** [comment]
k
