### ISSUE TITLE
Doesn't Make Portals Cursed or Immersive

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/immersive-cursedness#2]
[latest.log](https://github.com/TheEpicBlock/immersive-cursedness/files/5329373/latest.log)

Java version 8
Minecraft 1.16.2
Immersive Cursedness 1.1.0
Fabric API 0.20.1+build.401-1.16

**Comment by TheEpicBlock** [comment]
Seems like mixin is doing some weird stuff

**Comment by meisme-dev** [comment]
This happens for me too, logs are perfectly normal.

Java version 16
Minecraft 1.17.1
Immersive Cursedness 1.4.4
Fabric API-0.37

[latest.log](https://github.com/TheEpicBlock/immersive-cursedness/files/6941123/latest.log)

**Comment by TheEpicBlock** [comment]
Your issue is irrelevant to this one. But looking at the log you seem to be running Bukkit, not Fabric. Please open up a new issue if this persists.
