### ISSUE TITLE
Replay mod?

### ISSUE THREAD

**Issue by LordVenom77** [TheEpicBlock/immersive-cursedness#20]
The original Immersive Portals is incompatible with replay mod due to changes in how chunks and entities are saved or rendered. Is this mod compatible with replay?

**Comment by TheEpicBlock** [comment]
It should boot up at least. But due to the way immersive cursedness works it won't look right on the replay. The nether only looks correct from the players point of view. There's no way to resolve this it's just how immersive cursedness functions.
