### ISSUE TITLE
Portal atmosphere offsets from the camera in third-person view

### ISSUE THREAD

**Issue by EZForever** [TheEpicBlock/immersive-cursedness#26]
This bug pretty much broke the immersion. Tested on Minecraft 1.16.5 + Fabric Loader 0.11.6 + Fabric API 0.36.0+1.16 + Immersive Cursedness 1.3.2.

![2021-07-23_14 23 36](https://user-images.githubusercontent.com/34133756/126745605-d1052a13-ae9b-4b13-9886-8389bf0b2430.png)

![2021-07-23_14 23 54](https://user-images.githubusercontent.com/34133756/126745619-c5befb78-a0b5-4bb8-bb3b-c88264cfacbb.png)

---

Diving into the code, it seems that the atmosphere is created based on player entity's eye position, rather than the actual camera position:

https://github.com/TheEpicBlock/immersive-cursedness/blob/a2b18350af3b1f0fe2f347f77ff039e39a9c4281/src/main/java/nl/theepicblock/immersive_cursedness/PlayerManager.java#L92

Where `net.minecraft.entity.Entity#getCameraPosVec()` is defined like (Yarn 1.16.5+build.10-v2):

```java
public final Vec3d getCameraPosVec(float tickDelta) {
    if (tickDelta == 1.0F) {
        return new Vec3d(this.getX(), this.getEyeY(), this.getZ());
    } else {
        // ...
    }
}
```

However, since `net.minecraft.client.render.Camera` class is client-only, I doubt if this bug is actually fixable on server side.

**Comment by LoganDark** [comment]
The server has no idea whether the client's in f5 or not, yeah

**Comment by TheEpicBlock** [comment]
Yeah, I couldn't find any C2S packets telling the server f5 is on. Unless this is changed in a future update there's nothing Immersive Cursedness can do about this
