### ISSUE TITLE
Player Kicked for "Invalid Player Move Packet Recieved"

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/immersive-cursedness#3]
Java version 8
Minecraft 1.16.2
Immersive Cursedness 1.1.1
Fabric API 0.20.1+build.401-1.16

Walking into an area with fake blocks causes the player to be kicked for invalid player packet received.

**Comment by TheEpicBlock** [comment]
I'd say this is caused by #7, as you shouldn't be able to walk in an area with fake blocks
