### ISSUE TITLE
connection lost

### ISSUE THREAD

**Issue by SileyOf** [TheEpicBlock/immersive-cursedness#35]
I had a connection loss problem when I used minecraft version 1.18.2, Immersive Portals 1.4.0, Immersive Cursedness 1.4.5.
-From Google Translate
[1](https://img1.imgtp.com/2022/06/04/F1irMVgD.png)[2](https://img1.imgtp.com/2022/06/04/WZJpOcnj.png)

**Comment by TheEpicBlock** [comment]
Unfortunately this isn't enough info to debug your issue. Are you using immersive portals and immersive cursedness at the same time? If so that isn't supported
