### ISSUE TITLE
Does this mod only work with nether portals

### ISSUE THREAD

**Issue by chitinlink** [TheEpicBlock/immersive-cursedness#45]
I'm aware the mod isn't working in 1.19.3 yet (#43), but I have it installed and I only have access to the `/portal toggle` command.

Does this mod not have the functionality to add custom portals as with the normal Immersive Portals mod?
ie https://qouteall.fun/immptl/wiki/Portal-Customization.html#directly-create-portals

And if not, are there plans to add more functionality from the original mod?

**Comment by TheEpicBlock** [comment]
It only works with nether portals, yes. I don't have any plans to do custom portals unfortunately
