### ISSUE TITLE
You can't break blocks through dimensions 

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/immersive-cursedness#5]
Java version 8
Minecraft 1.16.2
Immersive Cursedness 1.1.1
Fabric API 0.20.1+build.401-1.16

Going through the portal makes the portal again. 
![2020-10-05_17 28 03](https://user-images.githubusercontent.com/66091019/95134099-49a05100-0730-11eb-9ac3-fe7f26bb5970.png)

**Comment by TheEpicBlock** [comment]
Added in 1.2.0
