### ISSUE TITLE
Large Parts of the Other Dimension Can Sometimes Appear as Ghost Blocks 

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/immersive-cursedness#7]
Java version 8
Minecraft 1.16.2
Immersive Cursedness 1.1.1
Fabric API 0.20.1+build.401-1.16

Last issue, I promise. This mod is really cool and I am amazed by what you have managed to do.
![2020-10-05_17 11 46](https://user-images.githubusercontent.com/66091019/95134697-4fe2fd00-0731-11eb-9a84-7705f29533cd.png)

**Comment by TheEpicBlock** [comment]
Note: since 1.2.0 this only seems to happen with multiple portals next to each other
